#!/bin/sh -
STATUS=100

if [ "$#" -ge 2 ]
then
    PORT=$1
    CONFIG=$2
    if [ -e $CONFIG ]
    then
        cp $CONFIG $(dirname $0)/config/device/
        filename=$(basename -- "$CONFIG")
        echo "changing netconf port with $PORT in netconf.json file ..."
        sed -i "/netconf-ssh-binding-port/c\  \"netconf-ssh-binding-port\" : "$PORT"," $(dirname $0)/config/netconf.json
        echo "changing persist-context and persist-config to false in honeycomb.json file ..."
        sed -i "/persist-context/c\  \"persist-context\" : \"false\"," $(dirname $0)/config/honeycomb.json
        sed -i "/persist-config/c\  \"persist-config\" : \"false\"," $(dirname $0)/config/honeycomb.json
        echo "changing netconf-initial-config-xml location with $CONFIG in honeycomb.json file ..."
        sed -i "/netconf-initial-config-xml/c\  \"netconf-initial-config-xml\" : \"device/$filename\"," $(dirname $0)/config/honeycomb.json
         while [ $STATUS -eq 100 ]
         do
           java -Xms512m -Xmn512m -Xmx1024m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=512m -jar $(dirname $0)/honeynode-distribution-1.18.01.jar
           STATUS=$?
           echo "Honeycomb exited with status: $STATUS"
           if [ $STATUS -eq 100 ]
           then
             echo "Restarting..."
           fi
         done
    else
        echo "initial config file doesn't exist !"
    fi
else 
    echo "honeycomb-tpce port initial-config-xml (option)pm-list-xml"
    echo "Eg : honeycomb-tpce 17832 sample-config-ROADM.xml pm-list.xml"
fi
