/*
 * Copyright © 2026 Orange, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.transportpce.tapisbi.rpcs;

import static java.util.Objects.requireNonNull;

import com.google.common.util.concurrent.ListenableFuture;
import org.opendaylight.transportpce.tapisbi.renderer.TapiSbiRendererService;
import org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.device.renderer.rev251001.ServicePath;
import org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.device.renderer.rev251001.ServicePathInput;
import org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.device.renderer.rev251001.ServicePathOutput;
import org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.device.renderer.rev251001.ServicePathOutputBuilder;
import org.opendaylight.yangtools.yang.common.RpcResult;
import org.opendaylight.yangtools.yang.common.RpcResultBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * This class is the implementation of the 'service-path' RESTCONF service.
 * It is is one of the external APIs into the renderer application.
 * For the specific case of services created through TAPI-SBI, rather than using service path to create connections
 * through the different devices, service path is used to build constraints (wavelength to use, nodes on the path), so
 * that the results of the path computation and the evaluation of impairment awareness is in line with the service
 * created through TAPI-SBI, which avoids potential source of crank-back.
 *
 * The service provides two functions:
 *
 * <p>1. Create This operation results in provisioning a service through TAPI-SBI for a given
 * wavelength and a list of nodes with each node listing its termination points.
 *
 * <p>2. Delete This operation results in de-provisioning a service through TAPI-SBI for a given
 * wavelength and a list of nodes with each node listing its termination points.
 *
 * <p>The signature for this method was generated by yang tools from the
 * renderer API model.
 */
public class TapiSbiServicePathImpl implements ServicePath {
    private static final Logger LOG = LoggerFactory.getLogger(TapiSbiServicePathImpl.class);
    private TapiSbiRendererService tapiSbiRendererService;

    public TapiSbiServicePathImpl(final TapiSbiRendererService tapiSbiRendererService) {
        this.tapiSbiRendererService = requireNonNull(tapiSbiRendererService);
    }

    @Override
    public ListenableFuture<RpcResult<ServicePathOutput>> invoke(ServicePathInput input) {
        if (input.getOperation() == null) {
            LOG.debug("A mandatory input argument is null");
            return RpcResultBuilder
                .success(new ServicePathOutputBuilder().setResult("Invalid operation").build())
                .buildFuture();
        }
        return switch (input.getOperation()) {
            case Create -> {
                LOG.info("Create operation request received");
                yield RpcResultBuilder.success(this.tapiSbiRendererService.createSbiService(input, null))
                    .buildFuture();
            }
            case Delete -> {
                LOG.info("Delete operation request received");
                yield RpcResultBuilder.success(this.tapiSbiRendererService.deleteSbiService(input))
                    .buildFuture();
            }
        };
    }
}
