---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: '^ordmodels/|.diff$'
        # ordmodels trailing blanks shall preferably be fixed in OpenROADM upstream repo

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
      - id: gitlint-ci
        stages: [manual]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
        stages: [commit]
        exclude: '^(.git/|docs/make.bat|docs/Makefile|ordmodels/)'

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
      - id: autopep8
        args: ['--in-place', '--max-line-length=120']

  - repo: https://github.com/perltidy/perltidy
    rev: '20240202.05'
    hooks:
      - id: perltidy
        stages: [commit]
