---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^ordmodels/|\.diff$|\.(xml|XML|yang|YANG|hex|HEX)$'
      - id: end-of-file-fixer
        exclude: '\.diff$|\.(xml|XML|yang|YANG|hex|HEX)$'
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        exclude: 'config_template\.json$|test-2-request-5-4\.json$'
      - id: mixed-line-ending
        exclude: '\.(xml|XML|yang|YANG|hex|HEX)$'

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
      - id: gitlint-ci
        stages: [manual]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        stages: [pre-commit]
        exclude: '^(.git/|docs/make.bat|docs/Makefile|ordmodels/)|\.(xml|XML|yang|YANG|hex|HEX)$'

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: ["--in-place", "--max-line-length=120"]

  - repo: https://github.com/perltidy/perltidy
    rev: "20240202.05"
    hooks:
      - id: perltidy
        stages: [pre-commit]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: "^tests/|^karaf/|^lighty/"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-commit]
        exclude: 'config_template\.json$|test-2-request-5-4\.json$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        types: [yaml]
