@startuml
'https://plantuml.com/sequence-diagram

autonumber

NotificationService -> ServiceHandlerListener:onServiceRpcResultSh()
== Case NotificationType ==\nServiceCreateResult\nServiceReconfigreResult\nServiceRestorationResult ==
ServiceHandlerListener -> FrequenciesService:allocateFrequencies(AtoZ,ZtoA)


@enduml
