<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opendaylight.mdsal</groupId>
    <artifactId>binding-parent</artifactId>
    <version>16.0.3</version>
    <relativePath/>
  </parent>

  <groupId>org.opendaylight.transportpce</groupId>
  <artifactId>transportpce-oc560-mapping</artifactId>
  <version>13.0.0-SNAPSHOT</version>
  <packaging>bundle</packaging>

  <properties>
    <transportpce.models.version>25.0.0-SNAPSHOT</transportpce.models.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.opendaylight.transportpce.models</groupId>
        <artifactId>transportpce-models-artifacts</artifactId>
        <version>${transportpce.models.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.opendaylight.transportpce.models</groupId>
      <artifactId>openconfig-platform-5.6.0</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce.models</groupId>
      <artifactId>openconfig-terminal-device-5.6.0</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce.models</groupId>
      <artifactId>openconfig-interfaces-5.6.0</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.transportpce.models</groupId>
      <artifactId>openconfig-transport-line-5.6.0</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>transportpce-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.mdsal</groupId>
      <artifactId>mdsal-binding-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.yangtools</groupId>
      <artifactId>yang-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opendaylight.yangtools</groupId>
      <artifactId>binding-spec</artifactId>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.component.annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Export-Package>
              org.opendaylight.transportpce.oc560.mapping.*
            </Export-Package>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
